-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- ColorMyPencils("rose-pine")
ColorMyPencils("rose-pine")
-- vim.cmd.colorscheme("rose-pine")
-- ColorMyPencils("rose-pine")
-- ColorMyPencils("nightfly")
-- vim.cmd.colorscheme("rose-pine")
-- vim.cmd.colorscheme("catppuccin-mocha")
-- ColorMyPencils("solarized-osaka")
-- ColorMyPencils("catppuccin-frappe")
-- vim.cmd.colorscheme("gruvbox")
-- vim.cmd.colorscheme("rose-pine")
-- vim.cmd.colorscheme("catppuccin")
-- vim.cmd.colorscheme("tokyonight")
